SELECT 
    MD_UPD_BATCH,
    MD_BATCH_ID,
    RCS_ADJUSTMENTS_TOTAL,
    ADJUSTMENT_TOTAL,
    TRANSFER_REBATES_TOTAL,
    MISC_CHARGES_TOTAL,
    WBC_CC_CHARGES_TOTAL,
    IPSC_CC_CHARGES_TOTAL,
    SESSION_BASED_CHARGES_TOTAL,
    USAGE_CHARGES_TOTAL,
    FLEXI_CEASE_TOTAL,
    TEST_SESSION_REQUEST_TOTAL,
    DISCOUNT_SUMMARY_TOTAL,
    WCC_CHARGES_TOTAL,
    ADVANCE_SERVICE_TOTAL,
    VOLUME_DISCOUNT_TOTAL,
    NON_PRODUCT_TYPE_TOTAL,
    EVENT_CHARGES_TOTAL,
    PERIODIC_CHARGES_TOTAL,
    ONE_OFF_CHARGES_TOTAL,
    INVOICE_TOTAL,
    NET_CHARGES_TOTAL,
    VAT_TOTAL,
    NET_TOTAL,
    BTB_BILL_YEAR_KEY,
    BTB_BILL_MONTH_KEY,
    BTB_FILE_KEY,
    INVOICE_REFERENCE,
    FILE_STATUS,
    FILE_NAME,
    MD_UPD_TS,
    MD_INS_TS,
    MD_EFFCTV_TO_TS,
    MD_EFFCTV_FROM_TS,
    MD_CURR_FLAG
FROM ODW_BTB_UIN_FILE_DIM
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
) OR (
    MD_UPD_TS >= '{from_ts}'
    AND MD_UPD_TS < '{to_ts}'
);
