SELECT
    BTB_CHALLENGE_KEY,
    DWH_REF_ID,
    CHALLENGE_COUNT,
    CHALLENGE_GROUP_ID,
    CHALLENGE_GROUP_NAME,
    DISPUTE_STATUS,
    DISPUTE_REASON,
    DISPUTE_SUB_REASON,
    DISPUTE_SUB_REASON_DESC,
    AUTOMATION_NAME,
    DISPUTED_AMOUNT,
    CHALLENGE_SENT_DATE,
    OR_REFERENCE,
    RESPONSE_DUE_DATE,
    RESPONSE_RCVD_DATE,
    REPLY_DECISION,
    REPLY_RESPONSE_TXT,
    REPLY_INVALID_REASON,
    WAIVED_AMOUNT,
    ACCEPTANCE_STATUS,
    FIRST_EDIT_BY,
    FIRST_EDIT_DATE,
    LAST_MODIFIED_BY,
    LAST_MODIFIED_DATE,
    MD_CURR_FLAG,
    MD_EFFCTV_FROM_TS,
    MD_EFFCTV_TO_TS,
    MD_INS_BATCH_ID,
    MD_INS_BATCH_TS,
    MD_UPD_BATCH_ID,
    MD_UPD_BATCH_TS
FROM ODW_BTB_CHALLENGE
WHERE (
    MD_INS_BATCH_TS >= '{from_ts}'
    AND MD_INS_BATCH_TS < '{to_ts}'
) OR (
    MD_UPD_BATCH_TS >= '{from_ts}'
    AND MD_UPD_BATCH_TS < '{to_ts}'
);
