SELECT
    NIM_SERVICE_KEY,
    NIM_SERVICE_ID,
    LEGACY_PATH_ID,
    PORT_NUMBER,
    CARD_NUMBER,
    ACCESS_NODE_NUMBER,
    EXCHANGE_CODE,
    SERVICE_TYPE,
    DIRECTORY_NUMBER,
    PROFILE_ID,
    RESERVED_DATE,
    LATEST_CONFIGURED_DATE,
    SERVICE_START_DATE,
    LATEST_COMMISSIONED_DATE,
    CANCELLED_DATE,
    CANCELLATION_EFF_DATE,
    NETWORK_PRODUCT_CODE,
    LINE_LENGTH,
    PORT_ID,
    SOURCE_SYSTEM,
    PRODUCT_UP_SPEED,
    PRODUCT_DOWN_SPEED,
    DATA_SNS_SERVICE_ID,
    VOICE_SNS_SERVICE_ID,
    NIM_OPERATOR_ID,
    ON_BNG,
    CGN_EXCLUSION_DATE,
    CGN_EXCLUSION_REASON,
    CGN_BLACKLIST_DATE,
    CGN_STATUS,
    UPDATED_DATE,
    MD_CURR_FLAG,
    MD_EFFCTV_FROM_TS,
    MD_EFFCTV_TO_TS,
    MD_INS_TS,
    MD_INS_INITIAL_BATCH_ID,
    MD_INS_ACTUAL_BATCH_ID,
    MD_UPD_TS,
    MD_UPD_INITIAL_BATCH_ID,
    MD_UPD_ACTUAL_BATCH_ID
FROM ODW_NIM_SERVICE_DIM
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
) OR (
    MD_UPD_TS >= '{from_ts}'
    AND MD_UPD_TS < '{to_ts}'
);
