SELECT
    MD_BATCH_ID,
    DATE_KEY,
    BTB_BILL_YEAR_KEY,
    BTB_BILL_MONTH_KEY,
    MD_INS_TS,
    END_OF_ADVANCE_MONTH,
    START_OF_ADVANCE_MONTH,
    END_CURRENT_MONTH,
    START_CURRENT_MONTH,
    BILL_TAX_DATE,
    BILL_MONTH
FROM ODW_BTB_BILL_MONTH_LU
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
);
