SELECT 
    LINE_TEST_SERVICE_TYPE_KEY,
    INIT_STAT,
    PORT_STAT,
    FAR_END_STATUS,
    NEAR_END_STATUS,
    SERVICE_LEVEL,
    SERVICE_TYPE,
    MD_INS_TS
FROM ODW_LINE_TEST_SERVICE_TYPE_DIM
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
);
