SELECT
    BTB_FILE_KEY,
    LANDED_ADJ_RECORDS,
    LANDED_ADJ_VALUE,
    LANDED_EVENT_RECORDS,
    LANDED_EVENT_VALUE,
    LANDED_PRODUCT_RECORDS,
    LANDED_PRODUCT_VALUE,
    WAREHOUSE_ADJ_RECORDS,
    WAREHOUSE_ADJ_VALUE,
    WAREHOUSE_EVENT_RECORDS,
    WAREHOUSE_EVENT_VALUE,
    WAREHOUSE_PRODUCT_RECORDS,
    WAREHOUSE_PRODUCT_VALUE,
    TOTAL_RECORDS_LANDED,
    TOTAL_LANDED_VALUE,
    TOTAL_RECORDS_WAREHOUSED,
    TOTAL_VALUE_WAREHOUSED,
    PROCESSED_DATETIME,
    MD_INS_TS
FROM ODW_BTB_BILL_AUDIT_DIM
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
);
