SELECT 
    MD_INS_BATCH_ID,
    EVENT_HISTORY_ID,
    SMP_AGENT_KEY,
    TROUBLE_REPORT_KEY,
    TROUBLE_REPORT_EVENT_TYPE_KEY,
    TROUBLE_REPORT_EVENT_HISTORY_KEY,
    NOTE,
    CREATED_BY,
    MD_INS_TS,
    CREATED_DATE
FROM ODW_TROUBLE_REPORT_EVENT_HISTORY_FACT
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
);
