SELECT 
    MD_BATCH_ID,
    BTB_BILL_TYPE_KEY,
    BILL_TYPE,
    VAT_STATUS,
    POST_CODE,
    ADDRESS_FIRST_LINE,
    ADDRESS_NAME,
    BUSINESS_NAME,
    ACCOUNT_REFERENCE,
    CUSTOMER_REFERENCE,
    SERVICE_TYPE,
    BILL_TITLE,
    MD_INS_TS
FROM ODW_BTB_BILL_TYPE_LU
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
);