SELECT 
    MD_BATCH_ID,
    BTB_BILL_TYPE_KEY,
    BTB_RECORD_TYPE_KEY,
    BTB_CHARGE_TYPE_KEY,
    BTB_CHARGE_SUB_TYPE_KEY,
    BTB_CHARGE_CODE_KEY,
    BTB_CHARGE_DESCRIPTION_KEY,
    CHARGE_DESCRIPTION,
    MD_INS_TS
FROM ODW_BTB_CHARGE_DESCRIPTION_LU
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
);
