SELECT 
    LINE_TEST_FAULT_KEY,
    FAULT_REPORT_ADVISED,
    FAULT_LOCATION,
    FAULT_CODE,
    MD_INS_TS
FROM ODW_LINE_TEST_FAULT_DIM
WHERE (
    MD_INS_TS >= '{from_ts}'
    AND MD_INS_TS < '{to_ts}'
);
